from .base_command import BaseCommand
from .serve import ServeCommand
from .login import LoginCommand
from .logout import LogoutCommand
from .register import RegisterCommand
from .workspace import WorkspaceCommand
#from .status import StatusCommand
#from .auth import AuthCommand
#from .add import AddCommand
#from .chat import ChatCommand
#from .examples import ExamplesCommand
